name: 'Tag PR'
inputs:
  token:
    description: 'A Github token'
    required: true
  build-tool:
    description: 'maven | npm'
    required: true
  app-type:
    description: 'spring-boot | npm-ui-lib'
    required: false
    
runs:
  using: "composite"
  steps:
    
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - uses: gustavogarayalde/github-actions/actions/build/maven@main
      if: ${{ inputs.build-tool == 'maven' }}

    - uses: gustavogarayalde/github-actions/actions/build/npm@main
      if: ${{ inputs.build-tool == 'npm' }}
      with:
        app-type: ${{ inputs.app-type }}
        token: ${{ inputs.token }}

    - name: Git Config
      shell: bash
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        echo "PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')" >> $GITHUB_ENV

    - name: Tag Version
      if: ${{ inputs.build-tool == 'maven'}}
      shell: bash
      run: git tag -a pr-${{ env.PR_NUMBER }}-$GITHUB_RUN_NUMBER -m "pr-${{ env.PR_NUMBER }}-$GITHUB_RUN_NUMBER"

    - name: Tag NPM Version
      if: ${{ inputs.build-tool == 'npm' }}
      shell: bash
      run: |
        npm version prerelease --preid=pr-${{ env.PR_NUMBER }}
        git push

    - uses: actions/checkout@v3
      with:
        token: ${{ inputs.token }}

    - name: Push tag to repo
      shell: bash
      run: git push --tags
