name: "Tag"
inputs:
  app-type:
    description: "spring-boot | npm-ui-lib"
    required: false
  build-tool:
    description: "maven | npm"
    required: true

runs:
  using: "composite"
  steps:
    - name: Git Config
      shell: bash
      run: |
        echo "PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')" >> $GITHUB_ENV

    - uses: actions/checkout@v3
      if: ${{ inputs.app-type == 'npm-ui-lib' }}
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Tag Version
      if: ${{ inputs.build-tool == 'maven' || inputs.app-type == 'next-js'}}
      shell: bash
      run: git tag -a pr-${{ env.PR_NUMBER }}-$GITHUB_RUN_NUMBER -m "pr-${{ env.PR_NUMBER }}-$GITHUB_RUN_NUMBER"

    - name: Tag NPM Lib Version
      if: ${{ inputs.app-type == 'npm-ui-lib' }}
      shell: bash
      run: |
        npm version prerelease --preid=pr-${{ env.PR_NUMBER }}
        git push