name: Push Docker Image on Tag

on:
  push:
    tags:
      - '*'

jobs:
  call-workflow-passing-data:
    uses: upcode-la/github-actions/.github/workflows/docker-on-tag.yml@main
    secrets:
      token: ${{ github.GITHUB_TOKEN }}
