name: Tag On Push to main

on:
  push:
    branches: [ main ]

jobs:
  call-workflow-passing-data:
    uses: upcode-la/github-actions/.github/workflows/tag-on-push-main.yml@main
    secrets:
      PAT: ${{ secrets.PAT }}
      token: ${{ github.token }}
