name: Tag On PR to main

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  call-workflow-passing-data:
    uses: upcode-la/github-actions/.github/workflows/tag-on-pr.yml@main
    secrets:
      PAT: ${{ secrets.PAT }}
