name: 'Publish'
inputs:
  repository:
    description: 'docker | maven'
    required: true
  build-tool:
    description: 'maven'
    required: true
  token:
    description: 'A Github Token'
    required: true
  app-type:
    description: 'spring-boot'
    required: true
  
runs:
  using: "composite"
  steps:
    - uses: gustavogarayalde/github-actions/actions/build/maven@main
      if: ${{ inputs.build-tool == 'maven'}}
    
    - uses: gustavogarayalde/github-actions/actions/publish/maven@main
      if: ${{ inputs.repository == 'maven'}}
      with:
        token: ${{ inputs.token }}
    
    - uses: gustavogarayalde/github-actions/actions/publish/docker@main
      if: ${{ inputs.repository == 'docker'}}
      with:
        token: ${{ inputs.token }}
        app-type: ${{ inputs.app-type }}
