name: "Publish"
inputs:
  token:
    description: "A Github Token"
    required: true
  app-type:
    description: "spring-boot | npm-ui-lib"
    required: true
  repository:
    description: "docker | maven | npm"
    required: true
  with-storybook:
    description: "true | false"
    required: false

runs:
  using: "composite"
  steps:
    - uses: gustavogarayalde/github-actions/actions/publish/maven@v0.0.15-rc
      if: ${{ inputs.repository == 'maven'}}
      with:
        token: ${{ inputs.token }}

    - uses: gustavogarayalde/github-actions/actions/publish/npm@v0.0.15-rc
      if: ${{ inputs.repository == 'npm'}}
      with:
        token: ${{ inputs.token }}

    - uses: gustavogarayalde/github-actions/actions/publish/docker@v0.0.15-rc
      if: ${{ inputs.repository == 'docker' || inputs.with-storybook == 'true' }}
      with:
        token: ${{ inputs.token }}
        app-type: ${{ inputs.app-type }}
