name: 'Publish'
inputs:
  repository:
    description: 'docker | maven'
    required: true
  build-tool:
    description: 'maven'
    required: true
  token:
    description: 'A Github Token'
    required: true
  
runs:
  using: "composite"
  steps:
    - uses: gustavogarayalde/github-actions/actions/publish/${{ inputs.build-tool }}@composite-actions
      with:
        token: ${{ inputs.token }}
