name: 'Release with NPM'
runs:
  using: "composite"
  steps:
    - name: Disable git hooks
      shell: bash
      run: git config core.hooksPath /dev/null

    - name: NPM Release
      shell: bash
      run: |
        CURRENT_VERSION=$(node -p "require('./package.json').version")
        BASE_VERSION=${CURRENT_VERSION%%-*}
        if [[ "$CURRENT_VERSION" == *-* ]]; then
          npm version "$BASE_VERSION"
        else
          npm version patch
        fi
