name: "Checkout Repository"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      if: ${{ github.event_name != 'pull_request' }}
      with:
        fetch-depth: 1
    
    - uses: actions/checkout@v4
      if: ${{ github.event_name == 'pull_request' }}
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        fetch-depth: 1