name: "Tag PR for Gradle"
inputs:
  app-type:
    description: "android-app"
    required: false
  build-tool:
    description: "gradle"
    required: true
  token:
    description: "Github Token"
    required: true

runs:
  using: "composite"
  steps:
    - name: Git Config
      shell: bash
      run: |
        git config user.email "action@github.com"
        git config user.name "GitHub Action"
        echo "PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')" >> $GITHUB_ENV

    - name: Tag Version
      shell: bash
      run: git tag -a pr-${{ env.PR_NUMBER }}-$GITHUB_RUN_NUMBER -m "pr-${{ env.PR_NUMBER }}-$GITHUB_RUN_NUMBER"

    - name: Download APK artifact
      uses: actions/download-artifact@v4
      with:
        name: android-apk
        path: apk-output

    - name: Download Bundle artifact
      uses: actions/download-artifact@v4
      with:
        name: android-bundle
        path: bundle-output

    - name: Find APK files
      shell: bash
      run: |
        APK_FILE=$(find apk-output -name "*.apk" -type f | head -1)
        echo "APK_FILE=$APK_FILE" >> $GITHUB_ENV
        AAB_FILE=$(find bundle-output -name "*.aab" -type f | head -1)
        echo "AAB_FILE=$AAB_FILE" >> $GITHUB_ENV

    - name: Create GitHub Release for PR
      uses: softprops/action-gh-release@v1
      with:
        tag_name: pr-${{ env.PR_NUMBER }}-$GITHUB_RUN_NUMBER
        name: PR #${{ env.PR_NUMBER }} - Build ${{ github.run_number }}
        body: |
          ## PR Build Artifacts
          
          Pull Request: #${{ env.PR_NUMBER }}
          Commit: ${{ github.sha }}
          
          Download the APK below to test this build on your device.
        files: |
          ${{ env.APK_FILE }}
          ${{ env.AAB_FILE }}
        draft: false
        prerelease: true
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
