name: 'Publish with Maven'
inputs:
  token:
    description: 'A Github token'
    required: true
runs:
  using: "composite"
  steps:
    - name: Publish to GitHub Packages Apache Maven
      shell: bash
      run: mvn deploy -DskipTests=true -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/${{ github.repository }}
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
