name: 'Publish with Docker'
inputs:
  token:
    description: 'A Github token'
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        registry: docker.pkg.github.com
        username: ${{ github.actor }}
        password: ${{ inputs.token }}
    -
      name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        file: ../../../dockerfiles/spring-boot/Dockerfile
        tags: ${{ github.repository }}/${{ github.event.repository.name }}:${{ env.GITHUB_REF }}

