name: 'Publish with Docker'
inputs:
  token:
    description: 'A Github token'
    required: true
  app-type:
    description: 'spring-boot'
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
          buildkitd-flags: --debug
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        registry: docker.pkg.github.com
        username: ${{ github.actor }}
        password: ${{ inputs.token }}
    
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        file: https://raw.githubusercontent.com/gustavogarayalde/github-actions/main/dockerfiles/${{ inputs.app-type }}/Dockerfile
        tags: docker.pkg.github.com/${{ github.repository }}/${{ github.event.repository.name }}:${{ github.ref_name }}
        secrets: |
            GIT_AUTH_TOKEN=${{ inputs.token }}

