name: 'Build and Release'
inputs:
  token:
    description: 'A Github token'
    required: true
  build-tool:
    description: 'maven | npm'
    required: true
runs:
  using: "composite"
  steps:

    - uses: actions/checkout@v3

    - uses: gustavogarayalde/github-actions/actions/build/maven@main
      if: ${{ inputs.build-tool == 'maven'}}

    - uses: gustavogarayalde/github-actions/actions/build/npm@main
      if: ${{ inputs.build-tool == 'npm'}}
      with:
        app-type: ${{ inputs.app-type }}
        token: ${{ inputs.token }}

    - name: Git Config
      shell: bash
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

    - uses: gustavogarayalde/github-actions/actions/release/maven@main
      if: ${{ inputs.build-tool == 'maven'}}
      with:
        token: ${{ github.token }}

    - uses: gustavogarayalde/github-actions/actions/release/npm@main
      if: ${{ inputs.build-tool == 'npm'}}

    - name: Push version bump to repo
      shell: bash
      run: git push

    - uses: actions/checkout@v3
      with:
        token: ${{ inputs.token }}

    - name: Push tag
      shell: bash
      run: git push --tags
