name: Publish on Tag

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: gustavogarayalde/github-actions/actions/publish@versionTag
      with:
        token: ${{ secrets.PAT }}
        build-tool: maven
        repository: maven
        app-type: spring-boot
