name: Publish on Tag

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    uses: gustavogarayalde/github-actions/actions/publish@composite-actions
    with:
      token: ${{ secrets.PAT }}
      build-tool: maven
      repository: maven
