name: Tag Release

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened]
permissions:
  contents: write

jobs:
  tag-release:
    runs-on: ubuntu-latest
    steps:
    - uses: gustavogarayalde/github-actions/actions/tag-release@versionTag
      with:
        token: ${{ secrets.PAT }}
        build-tool: maven # maven | npm | gradle
        repository: maven # maven | npm | docker | google-play
        app-type: spring-boot # spring-boot | npm-ui-lib | android-app
        settings-url: raw.githubusercontent.com/OWNER/devops/main/maven/settings.xml # only for maven build-tool
        # Android-specific parameters (only for gradle build-tool & google-play repository):
        # service-account-json: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON }}
        # package-name: com.yourcompany.yourapp
        # track: internal # internal | alpha | beta | production
