name: Tag On Push to main

on:
  push:
    branches: [ main ]
permissions:
  contents: write

jobs:
  call-workflow-passing-data:
    uses: gustavogarayalde/github-actions/actions/tag/release@composite-actions
    with:
      token: ${{ secrets.PAT }}
      build-tool: maven
