name: Tag Release

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened]
permissions:
  contents: write

jobs:
  tag-release:
    runs-on: ubuntu-latest
    steps:
    - uses: gustavogarayalde/github-actions/actions/tag-release@versionTag
      with:
        token: ${{ secrets.PAT }}
        build-tool: maven
        repository: maven
        app-type: spring-boot
        settings-url: raw.githubusercontent.com/OWNER/devops/main/maven/settings.xml # only for maven build-tool
