name: Tag PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  tag-pr:
    uses: gustavogarayalde/github-actions/actions/tag/pr@composite-actions
    with:
      token: ${{ secrets.PAT }}
      build-tool: maven
