name: Unit and E2E Tests

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: gustavogarayalde/github-actions/actions/test/maven@versionTag
        with:
          token: ${{ secrets.PAT }}
          settings-url: raw.githubusercontent.com/OWNER/devops/main/maven/settings.xml
