name: Push Docker Image on Tag

on:
  workflow_call:
    secrets:
      token:
        required: true

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 1.11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
        cache: 'maven'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Push to GitHub Packages
      uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.token }}
        registry: docker.pkg.github.com
        repository: ${{ github.repository }}/${{ github.event.repository.name }}
        tag_with_ref: true
