name: Tag On Push to main

on:
  workflow_call:
    secrets:
      PAT:
        required: true
      token:
        required: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 1.11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
        cache: 'maven'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Maven Release
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        mvn --batch-mode clean build-helper:parse-version release:prepare -DdevelopmentVersion=\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.\${parsedVersion.nextIncrementalVersion}-SNAPSHOT -DpushChanges=false
      env:
        GITHUB_TOKEN: ${{ secrets.token }}
    - name: Push to repo
      run: git push

    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.PAT }}

    - name: Push tag
      run: git push --tags
