name: Tag On PR to main (Reusable)

on:
  workflow_call:
    secrets:
      PAT:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 1.11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Tag version
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
          git tag -a pr-$PR_NUMBER-$GITHUB_RUN_NUMBER -m "pr-$PR_NUMBER-$GITHUB_RUN_NUMBER"
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
      - name: Push tag to repo
        run: git push --tags
